<?php

namespace Database\Seeders;

use Faker\Calculator\Isbn;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        /* 
        DB::table('books')->insert([
            [
                'isbn' => '0195153448',
                'title' => 'Classical Mythology',
                'author' => 'Mark P. O. Morford',
                'year_publication_at' => '2002',
                'publisher' => 'Oxford University Press',
                'cover_url_s' => 'http://images.amazon.com/images/P/0195153448.01.THUMBZZZ.jpg',
                'cover_url_m' => 'http://images.amazon.com/images/P/0195153448.01.MZZZZZZZ.jpg',
                'cover_url_l' => 'http://images.amazon.com/images/P/0195153448.01.LZZZZZZZ.jpg',
            ],
            [
                'isbn' => '0002005018',
                'title' => 'Clara Callan',
                'author' => 'Richard Bruce Wright',
                'year_publication_at' => '2001',
                'publisher' => 'HarperFlamingo Canada',
                'cover_url_s' => 'http://images.amazon.com/images/P/0002005018.01.THUMBZZZ.jpg',
                'cover_url_m' => 'http://images.amazon.com/images/P/0002005018.01.MZZZZZZZ.jpg',
                'cover_url_l' => 'http://images.amazon.com/images/P/0002005018.01.LZZZZZZZ.jpg',
            ],
            [
                'isbn' => "0060973129",
                'title' => "Decision in Normandy",
                'author' => "Carlo D'Este",
                'year_publication_at' => "1991",
                'publisher' => "HarperPerennial",
                'cover_url_s' => "http://images.amazon.com/images/P/0060973129.01.THUMBZZZ.jpg",
                'cover_url_m' => "http://images.amazon.com/images/P/0060973129.01.MZZZZZZZ.jpg",
                'cover_url_l' => "http://images.amazon.com/images/P/0060973129.01.LZZZZZZZ.jpg",
            ],
            [
                'isbn' => "0374157065",
                'title' => "Flu: The Story of the Great Influenza Pandemic of 1918 and the Search for the Virus That Caused It",
                'author' => "Gina Bari Kolata",
                'year_publication_at' => "1999",
                'publisher' => "Farrar Straus Giroux",
                'cover_url_s' => "http://images.amazon.com/images/P/0374157065.01.THUMBZZZ.jpg",
                'cover_url_m' => "http://images.amazon.com/images/P/0374157065.01.MZZZZZZZ.jpg",
                'cover_url_l' => "http://images.amazon.com/images/P/0374157065.01.LZZZZZZZ.jpg",
            ],
            [
                'isbn' => "0393045218",
                'title' => "The Mummies of Urumchi",
                'author' => "E. J. W. Barber",
                'year_publication_at' => "1999",
                'publisher' => "W. W. Norton &amp; Company",
                'cover_url_s' => "http://images.amazon.com/images/P/0393045218.01.THUMBZZZ.jpg",
                'cover_url_m' => "http://images.amazon.com/images/P/0393045218.01.MZZZZZZZ.jpg",
                'cover_url_l' => "http://images.amazon.com/images/P/0393045218.01.LZZZZZZZ.jpg",
            ],
            [
                'isbn' => "0399135782",
                'title' => "The Kitchen God's Wife",
                'author' => "Amy Tan",
                'year_publication_at' => "1991",
                'publisher' => "Putnam Pub Group",
                'cover_url_s' => "http://images.amazon.com/images/P/0399135782.01.THUMBZZZ.jpg",
                'cover_url_m' => "http://images.amazon.com/images/P/0399135782.01.MZZZZZZZ.jpg",
                'cover_url_l' => "http://images.amazon.com/images/P/0399135782.01.LZZZZZZZ.jpg",
            ],
            [
                'isbn' => "0425176428",
                'title' => "What If?: The World's Foremost Military Historians Imagine What Might Have Been",
                'author' => "Robert Cowley",
                'year_publication_at' => "2000",
                'publisher' => "Berkley Publishing Group",
                'cover_url_s' => "http://images.amazon.com/images/P/0425176428.01.THUMBZZZ.jpg",
                'cover_url_m' => "http://images.amazon.com/images/P/0425176428.01.MZZZZZZZ.jpg",
                'cover_url_l' => "http://images.amazon.com/images/P/0425176428.01.LZZZZZZZ.jpg",
            ],
            [
                'isbn' => "0671870432",
                'title' => "PLEADING GUILTY",
                'author' => "Scott Turow",
                'year_publication_at' => "1993",
                'publisher' => "Audioworks",
                'cover_url_s' => "http://images.amazon.com/images/P/0671870432.01.THUMBZZZ.jpg",
                'cover_url_m' => "http://images.amazon.com/images/P/0671870432.01.MZZZZZZZ.jpg",
                'cover_url_l' => "http://images.amazon.com/images/P/0671870432.01.LZZZZZZZ.jpg",
            ],
            [
                'isbn' => "0679425608",
                'title' => "Under the Black Flag: The Romance and the Reality of Life Among the Pirates",
                'author' => "David Cordingly",
                'year_publication_at' => "1996",
                'publisher' => "Random House",
                'cover_url_s' => "http://images.amazon.com/images/P/0679425608.01.THUMBZZZ.jpg",
                'cover_url_m' => "http://images.amazon.com/images/P/0679425608.01.MZZZZZZZ.jpg",
                'cover_url_l' => "http://images.amazon.com/images/P/0679425608.01.LZZZZZZZ.jpg",
            ],
            [
                'isbn' => "074322678X",
                'title' => "Where You'll Find Me: And Other Stories",
                'author' => "Ann Beattie",
                'year_publication_at' => "2002",
                'publisher' => "Scribner",
                'cover_url_s' => "http://images.amazon.com/images/P/074322678X.01.THUMBZZZ.jpg",
                'cover_url_m' => "http://images.amazon.com/images/P/074322678X.01.MZZZZZZZ.jpg",
                'cover_url_l' => "http://images.amazon.com/images/P/074322678X.01.LZZZZZZZ.jpg",
            ],
            [
                'isbn' => "0771074670",
                'title' => "Nights Below Station Street",
                'author' => "David Adams Richards",
                'year_publication_at' => "1988",
                'publisher' => "Emblem Editions",
                'cover_url_s' => "http://images.amazon.com/images/P/0771074670.01.THUMBZZZ.jpg",
                'cover_url_m' => "http://images.amazon.com/images/P/0771074670.01.MZZZZZZZ.jpg",
                'cover_url_l' => "http://images.amazon.com/images/P/0771074670.01.LZZZZZZZ.jpg",
            ],
            [
                'isbn' => "080652121X",
                'title' => "Hitler's Secret Bankers: The Myth of Swiss Neutrality During the Holocaust",
                'author' => "Adam Lebor",
                'year_publication_at' => "2000",
                'publisher' => "Citadel Press",
                'cover_url_s' => "http://images.amazon.com/images/P/080652121X.01.THUMBZZZ.jpg",
                'cover_url_m' => "http://images.amazon.com/images/P/080652121X.01.MZZZZZZZ.jpg",
                'cover_url_l' => "http://images.amazon.com/images/P/080652121X.01.LZZZZZZZ.jpg",
            ],
            [
                'isbn' => "0887841740",
                'title' => "The Middle Stories",
                'author' => "Sheila Heti",
                'year_publication_at' => "2004",
                'publisher' => "House of Anansi Press",
                'cover_url_s' => "http://images.amazon.com/images/P/0887841740.01.THUMBZZZ.jpg",
                'cover_url_m' => "http://images.amazon.com/images/P/0887841740.01.MZZZZZZZ.jpg",
                'cover_url_l' => "http://images.amazon.com/images/P/0887841740.01.LZZZZZZZ.jpg",
            ],
            [
                'isbn' => "1552041778",
                'title' => "Jane Doe",
                'author' => "R. J. Kaiser",
                'year_publication_at' => "1999",
                'publisher' => "Mira Books",
                'cover_url_s' => "http://images.amazon.com/images/P/1552041778.01.THUMBZZZ.jpg",
                'cover_url_m' => "http://images.amazon.com/images/P/1552041778.01.MZZZZZZZ.jpg",
                'cover_url_l' => "http://images.amazon.com/images/P/1552041778.01.LZZZZZZZ.jpg",
            ],
            [
                'isbn' => "1558746218",
                'title' => "A Second Chicken Soup for the Woman's Soul (Chicken Soup for the Soul Series)",
                'author' => "Jack Canfield",
                'year_publication_at' => "1998",
                'publisher' => "Health Communications",
                'cover_url_s' => "http://images.amazon.com/images/P/1558746218.01.THUMBZZZ.jpg",
                'cover_url_m' => "http://images.amazon.com/images/P/1558746218.01.MZZZZZZZ.jpg",
                'cover_url_l' => "http://images.amazon.com/images/P/1558746218.01.LZZZZZZZ.jpg",
            ],
            [
                'isbn' => "1567407781",
                'title' => "The Witchfinder (Amos Walker Mystery Series)",
                'author' => "Loren D. Estleman",
                'year_publication_at' => "1998",
                'publisher' => "Brilliance Audio - Trade",
                'cover_url_s' => "http://images.amazon.com/images/P/1567407781.01.THUMBZZZ.jpg",
                'cover_url_m' => "http://images.amazon.com/images/P/1567407781.01.MZZZZZZZ.jpg",
                'cover_url_l' => "http://images.amazon.com/images/P/1567407781.01.LZZZZZZZ.jpg",
            ],
            [
                'isbn' => "1575663937",
                'title' => "More Cunning Than Man: A Social History of Rats and Man",
                'author' => "Robert Hendrickson",
                'year_publication_at' => "1999",
                'publisher' => "Kensington Publishing Corp.",
                'cover_url_s' => "http://images.amazon.com/images/P/1575663937.01.THUMBZZZ.jpg",
                'cover_url_m' => "http://images.amazon.com/images/P/1575663937.01.MZZZZZZZ.jpg",
                'cover_url_l' => "http://images.amazon.com/images/P/1575663937.01.LZZZZZZZ.jpg",
            ],
            [
                'isbn' => "1881320189",
                'title' => "Goodbye to the Buttermilk Sky",
                'author' => "Julia Oliver",
                'year_publication_at' => "1994",
                'publisher' => "River City Pub",
                'cover_url_s' => "http://images.amazon.com/images/P/1881320189.01.THUMBZZZ.jpg",
                'cover_url_m' => "http://images.amazon.com/images/P/1881320189.01.MZZZZZZZ.jpg",
                'cover_url_l' => "http://images.amazon.com/images/P/1881320189.01.LZZZZZZZ.jpg",
            ],
            [
                'isbn' => "0440234743",
                'title' => "The Testament",
                'author' => "John Grisham",
                'year_publication_at' => "1999",
                'publisher' => "Dell",
                'cover_url_s' => "http://images.amazon.com/images/P/0440234743.01.THUMBZZZ.jpg",
                'cover_url_m' => "http://images.amazon.com/images/P/0440234743.01.MZZZZZZZ.jpg",
                'cover_url_l' => "http://images.amazon.com/images/P/0440234743.01.LZZZZZZZ.jpg",
            ],
            [
                'isbn' => "0452264464",
                'title' => "Beloved (Plume Contemporary Fiction)",
                'author' => "Toni Morrison",
                'year_publication_at' => "1994",
                'publisher' => "Plume",
                'cover_url_s' => "http://images.amazon.com/images/P/0452264464.01.THUMBZZZ.jpg",
                'cover_url_m' => "http://images.amazon.com/images/P/0452264464.01.MZZZZZZZ.jpg",
                'cover_url_l' => "http://images.amazon.com/images/P/0452264464.01.LZZZZZZZ.jpg",
            ],
            [
                'isbn' => "0609804618",
                'title' => "Our Dumb Century: The Onion Presents 100 Years of Headlines from America's Finest News Source",
                'author' => "The Onion",
                'year_publication_at' => "1999",
                'publisher' => "Three Rivers Press",
                'cover_url_s' => "http://images.amazon.com/images/P/0609804618.01.THUMBZZZ.jpg",
                'cover_url_m' => "http://images.amazon.com/images/P/0609804618.01.MZZZZZZZ.jpg",
                'cover_url_l' => "http://images.amazon.com/images/P/0609804618.01.LZZZZZZZ.jpg",
            ]
        ]);
        */

        DB::table('books')->insert([
            [
                'isbn' => "038550120X",
                'title' => "A Painted House",
                'author' => "JOHN GRISHAM",
                'year_publication_at' => "2001",
                'publisher' => "Doubleday",
                'cover_url_s' => "http://images.amazon.com/images/P/038550120X.01.THUMBZZZ.jpg",
                'cover_url_m' => "http://images.amazon.com/images/P/038550120X.01.MZZZZZZZ.jpg",
                'cover_url_l' => "http://images.amazon.com/images/P/038550120X.01.LZZZZZZZ.jpg",
            ],
            [
                'isbn' => "034545104X",
                'title' => "Flesh Tones: A Novel",
                'author' => "M. J. Rose",
                'year_publication_at' => "2002",
                'publisher' => "Ballantine Books",
                'cover_url_s' => "http://images.amazon.com/images/P/034545104X.01.THUMBZZZ.jpg",
                'cover_url_m' => "http://images.amazon.com/images/P/034545104X.01.MZZZZZZZ.jpg",
                'cover_url_l' => "http://images.amazon.com/images/P/034545104X.01.LZZZZZZZ.jpg",
            ],
            [
                'isbn' => "0446520802",
                'title' => "The Notebook",
                'author' => "Nicholas Sparks",
                'year_publication_at' => "1996",
                'publisher' => "Warner Books",
                'cover_url_s' => "http://images.amazon.com/images/P/0446520802.01.THUMBZZZ.jpg",
                'cover_url_m' => "http://images.amazon.com/images/P/0446520802.01.MZZZZZZZ.jpg",
                'cover_url_l' => "http://images.amazon.com/images/P/0446520802.01.LZZZZZZZ.jpg",
            ],
            [
                'isbn' => "0425115801",
                'title' => "Lightning",
                'author' => "Dean R. Koontz",
                'year_publication_at' => "1996",
                'publisher' => "Berkley Publishing Group",
                'cover_url_s' => "http://images.amazon.com/images/P/0425115801.01.THUMBZZZ.jpg",
                'cover_url_m' => "http://images.amazon.com/images/P/0425115801.01.MZZZZZZZ.jpg",
                'cover_url_l' => "http://images.amazon.com/images/P/0425115801.01.LZZZZZZZ.jpg",
            ],
            [
                'isbn' => "055356451X",
                'title' => "Night Sins",
                'author' => "TAMI HOAG",
                'year_publication_at' => "1995",
                'publisher' => "Bantam",
                'cover_url_s' => "http://images.amazon.com/images/P/055356451X.01.THUMBZZZ.jpg",
                'cover_url_m' => "http://images.amazon.com/images/P/055356451X.01.MZZZZZZZ.jpg",
                'cover_url_l' => "http://images.amazon.com/images/P/055356451X.01.LZZZZZZZ.jpg",
            ],
        ]);
    }
}
